# Generated by Django 3.1.2 on 2020-10-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predictions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UUID', models.BigIntegerField(unique=True)),
                ('truckLicenseNumber', models.CharField(max_length=7, unique=True)),
                ('truckModelNumber', models.CharField(max_length=10)),
                ('dateTime', models.DateTimeField()),
                ('currentSpeed', models.FloatField(null=True)),
                ('totalFuelUsed', models.FloatField(null=True)),
                ('rpm', models.FloatField(null=True)),
                ('totalDistance', models.FloatField(null=True)),
                ('wheelSpeed', models.FloatField(null=True)),
                ('engineLoad', models.FloatField(null=True)),
                ('engineHours', models.FloatField(null=True)),
                ('nextMaintenance', models.IntegerField(null=True)),
            ],
        ),
    ]
