# Generated by Django 3.1.2 on 2020-10-31 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictiveModel', '0002_predictions_enginetemp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictions',
            name='UUID',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='predictions',
            name='truckLicenseNumber',
            field=models.CharField(max_length=7),
        ),
    ]
