# Generated by Django 3.1.2 on 2021-01-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictiveModel', '0004_auto_20210103_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictions',
            name='harsh_acceleration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='predictions',
            name='harsh_braking',
            field=models.IntegerField(null=True),
        ),
    ]
