# Generated by Django 3.1.2 on 2021-01-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictiveModel', '0005_auto_20210106_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictions',
            name='UUID',
            field=models.CharField(max_length=15),
        ),
    ]
