# Generated by Django 3.1.2 on 2021-01-06 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictiveModel', '0006_auto_20210106_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictions',
            name='harsh_acceleration',
        ),
        migrations.RemoveField(
            model_name='predictions',
            name='harsh_braking',
        ),
    ]
